### ISSUE TITLE
Create ui for clock interface

### ISSUE THREAD

**Issue by gnrlbzik** [KorolevskiTigr2/BYBYBY#3]
# Description

We need basic visual representation in HTML/CSS of time zone clock conversion. This is not a interactive, just a basic view to get things going

# Acceptance Criteria

- When user views our interface, then it can see a analog local clock

# TODO
- [x] bootstarp html/css code
- [x] create analog clock
  - [x] create dial
  - [x] create hours hand
  - [x] create minutes hand
  - [x] create seconds hand

# VISUAL ASSETS
![CleanShot 2022-07-08 at 12 50 14](https://user-images.githubusercontent.com/658148/178044457-2b7166d1-530e-4e82-97e8-108191c26266.png)

![image](https://user-images.githubusercontent.com/106224753/176759043-1aa85d29-e635-474c-afa4-dc02aceb12b4.png)
