### ISSUE TITLE
Convert current html/css into webcomponents

### ISSUE THREAD

**Issue by gnrlbzik** [KorolevskiTigr2/BYBYBY#8]
# Description

We need to convert our current html/css code into web components. So we need to bootstrap basic webcomponents boilerplate project code and then convert our html/css into web components standard code.

# Acceptance Criteria

- Code base is modified to the requirements of webcomponents standards

# TODO

- [ ] make sure that our code base is matching webcomponents requirements
- [ ] convert existing code into webcomponents
- [ ] create landing page (home dashboard) that ties all webcomponents together (no interactivity)

# RESOURCES

- https://developer.mozilla.org/en-US/docs/Web/Web_Components
- https://open-wc.org/ / https://github.com/open-wc/open-wc

# VISUAL ASSETS

![image](https://user-images.githubusercontent.com/106224753/176759043-1aa85d29-e635-474c-afa4-dc02aceb12b4.png)
